//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EtherscanTest
{
    using System;
    using System.Collections.Generic;
    
    public partial class transaction
    {
        public int transactionID { get; set; }
        public int blockID { get; set; }
        public string hash { get; set; }
        public string fromAddress { get; set; }
        public string toAddress { get; set; }
        public decimal value { get; set; }
        public decimal gas { get; set; }
        public decimal gasPrice { get; set; }
        public int transactionIndex { get; set; }
    
        public virtual block block { get; set; }
    }
}
